name: Deploy Site

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Mensagem'
        required: true
        default: 'Deploy Manual Site'
  push:
    branches:
      - main
    paths:
      - 'lib/**'
      - '.storybook/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.20.0

      - name: Install dependencies
        run: rm -rf node_modules && npm i

      - name: Build project
        run: npm run build-storybook

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifact-site
          path: storybook-static

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifact-site
          path: storybook-static

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::890620372383:role/github-actions-sls
          aws-region: us-east-1

      - name: Deploy static site to S3 bucket
        run: |
          aws s3 sync dist/apps/ac/ s3://cp-aurora-ui-production-sa-east-1/ \
          --exclude '*.gitkeep' \
          --exclude '*.html' \
          --cache-control 'max-age=3888000' \ 
          --delete

          aws s3 sync dist/apps/ac/ s3://cp-aurora-ui-production-sa-east-1/ \
          --exclude '*' \
          --include '*.html' \
          --cache-control 'no-cache, no-store' \ 
          --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id E1X8RBYTJLAH84 --paths "/*"
