name: Publish Lib (npm)
on:
  pull_request:
    branches:
      - main
    paths:
      - 'lib/**'
      - 'package.json'
    types: [closed]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.18.0
          registry-url: 'https://registry.npmjs.org'

      - name: Git Identity
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY

      - name: Install dependencies
        run: |
          rm -rf node_modules
          npm ci

      - name: Bump version
        run: npm version patch --no-git-tag-version

      - name: Commit version bump
        run: |
          git add package.json
          git commit -m "chore: bump version to $(node -p "require('./package.json').version")"

      - name: Create Git Tag
        run: git tag v$(node -p "require('./package.json').version")

      - name: Build lib
        run: npm run build

      - name: Publish to npm
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}