name: Release & Publish

on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  release-please:
    # Execute apenas quando o PR foi mesclado (não quando foi fechado sem merge)
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      version: ${{ steps.release.outputs.version }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: '@consumidor-positivo/aurora'
          changelog-types: |
            [
              {"type": "feat", "section": "Features", "hidden": false},
              {"type": "fix", "section": "Bug Fixes", "hidden": false},
              {"type": "docs", "section": "Documentation", "hidden": false},
              {"type": "chore", "section": "Maintenance", "hidden": false},
              {"type": "refactor", "section": "Code Refactoring", "hidden": false, "bump": "patch"},
              {"type": "test", "section": "Tests", "hidden": false},
              {"type": "ci", "section": "CI/CD", "hidden": true}
            ]

  publish:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false # never use caching in release builds

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build storybook
        run: npm run build-storybook

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: us-east-1

      - name: Deploy static site to S3 bucket
        run: |
          aws s3 sync storybook-static/ s3://${{ vars.AWS_S3_BUCKET }} \
          --exclude '*.gitkeep' \
          --exclude '*.html' \
          --cache-control 'max-age=3888000' \
          --delete

          aws s3 sync storybook-static/ s3://${{ vars.AWS_S3_BUCKET }} \
          --exclude '*' \
          --include '*.html' \
          --cache-control 'no-cache, no-store' \
          --delete

          # Wait for all S3 operations to complete
          wait

          # Invalidate CloudFront cache
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"

  notify-consumers:
    needs: [release-please, publish]
    uses: AcordoCertoBR/actions/.github/workflows/node-lib-update-dispatcher.yml@main
    with:
      package-name: '@consumidor-positivo/aurora'
      reviewers: 'gi-flor'
      version: ${{ needs.release-please.outputs.version }}
    secrets:
      app-id: ${{ vars.CREATE_PR_CP_APP_ID }}
      app-private-key: ${{ secrets.CREATE_PR_CP_APP_PRIVATE_KEY }}
